---
version: "3"
services:
 devopsdb:
   image:  saideep6633/myrepo1:dbimage
   ports:
     - "3306:3306"

 application:
   image:  saideep6633/myrepo1:appimage
   ports:
     - " 1111:8080 "
   depends_on:
     - "devopsdb"
